### ISSUE TITLE
反対側の壁にくっつく際のカメラの向きを修正する

### ISSUE THREAD

**Issue by Saturn2525** [harumas/Gravity-Wall#134]
反対側の壁に飛び移った際にカメラがもとの方向の逆を向いてしまうので、もとの方向を向いたままになるようにしてください。

**Comment by harumas** [comment]
反対側の壁というのは天井に対してジャンプしたときということですか？
元の方向の逆を向いてしまうの意味を知りたいので、画像など貼ってくれるとありがたいです。

**Comment by Saturn2525** [comment]
進行方向の後ろを向いてしまう状態です
![image](https://github.com/user-attachments/assets/052dd62a-92f9-4c61-971b-a06d6a902a48)
![image](https://github.com/user-attachments/assets/932379c6-0438-4ef9-9c27-221690affbfc)
今は壁と垂直な軸で回転しており、向いていた方向と反対を向いてしまいます
![image](https://github.com/user-attachments/assets/4f6eb0fc-53ed-43ee-abb9-3eeb752eb3b2)
