### ISSUE TITLE
パズル部屋カメラ処理を変更する

### ISSUE THREAD

**Issue by Mocha0924** [harumas/Gravity-Wall#148]
[パズル部屋カメラ仕様.pdf](https://github.com/user-attachments/files/17113225/default.pdf)

pdfに内容を記入しました。わからないことがあれば聞いてください

**Comment by MettoNao** [comment]
固定カメラはここのブランチで実装しています。
伝え忘れていました...
https://github.com/harumas/Gravity-Wall/tree/fix/hole-in

**Comment by harumas** [comment]
feature/hole-in-cameraで一応実装はしましたが詰まっています。実用レベルではないです。
理由としては、90度を維持するのが難しい感じです。
スティックによる角度変更、プレイヤーの重力変更による角度変更、その他の不明な要因で角度が途中でずれてしまいます。
角度変更中は重力変更できないようにするなど試してみたのですが、ずれてしまいました。

実装の方法を変える必要があるので、もう少し時間がかかりそうです。

**Comment by Mocha0924** [comment]
プレイヤーが角付近で斜めに張り付こうとすると、カメラが移動しないバグを発見しました
https://github.com/user-attachments/assets/ffa7296b-0d5c-4843-8ad0-3e222689dd9b

**Comment by harumas** [comment]
壁に垂直な重力が確定しないとカメラを移動しないようにしているので、斜めに張り付くことは現状できないです。
90度以外でカメラを動かすと複雑になってしまうので、できれば避けたいです。

**Comment by Mocha0924** [comment]
カメラが移動しないことはバグではなく、角にできる空間で歩けてしまうバグが原因という認識であっていますか

**Comment by harumas** [comment]
そうですね。
垂直にならないとカメラが移動しないので、角にピッタリ斜め入力ができてしまい、角の空間で歩けてしまいます。

**Comment by Mocha0924** [comment]
角の空間を歩けてしまうバグを直すのは難しそうですかね
