### ISSUE TITLE
ディザ抜きの導入

### ISSUE THREAD

**Issue by MettoNao** [harumas/Gravity-Wall#16]
* ドアなどの出っ張りにカメラが入ると壁が全て消えてしまう不具合の修正

![Image](https://github.com/harumas/Gravity-Wall/assets/61572900/6f0f0952-9f6f-44b3-b491-e06079ecdbbb)

![Image](https://github.com/harumas/Gravity-Wall/assets/61572900/c5d5355e-6131-4f51-9cb1-d91b76bc066d)

**Comment by harumas** [comment]
ディザ抜きの導入
