### ISSUE TITLE
ゲートの裏側が見えてしまう場合のみ、ゲートを非表示にする

### ISSUE THREAD

**Issue by Mocha0924** [harumas/Gravity-Wall#176]
ゲートの裏側がパズルを解くのに邪魔なので、ゲートの裏側が表示されないようにしてください
![Image](https://github.com/user-attachments/assets/168dbc6c-da4c-483f-afcd-b20d28edb835)

**Comment by harumas** [comment]
この仕様はHole-inだけの仕様ですか？
他のステージでも同様に扉を非表示にしたいのであれば、ゲート共通の機能として実装します。

**Comment by MettoNao** [comment]
パズルステージのみの仕様+透過する対象を扉に限定したく無いので
透過したい対象にコンポーネントをアタッチする形式でお願いしたいです
