### ISSUE TITLE
右スティック(マウス)でカメラを上下左右に操作できるようにする

### ISSUE THREAD

**Issue by MettoNao** [harumas/Gravity-Wall#19]

**Comment by harumas** [comment]
プレイヤーの向きはどうする？

**Comment by MettoNao** [comment]
TPSみたいにプレイヤーの向きがカメラに追従するかって事？
それなら、プレイヤーの向きはカメラに追従しないようにお願い

**Comment by harumas** [comment]
pushしました

**Comment by MettoNao** [comment]
実装ありがとう。
概ね良いけど、カメラを上に向けると床をすり抜けちゃうのは避けたいかもしれない。
上を向く時だけPlayerにカメラが寄ってく形のカメラも試してみたい。
実装お願いできそう？

**Comment by harumas** [comment]
もう少し詳しく聞いてもいいか?
カメラが体の下半身ぐらいまで下がったら、それに比例してカメラが寄ってくるってことでいい？

**Comment by MettoNao** [comment]
> カメラが体の下半身ぐらいまで下がったら、それに比例してカメラが寄ってくるってことでいい？
この認識で大丈夫です。

こんな感じのイメージ


![Image](https://github.com/harumas/Gravity-Wall/assets/61572900/348fc383-dca0-4e6a-9c61-10701112ab09)

![Image](https://github.com/harumas/Gravity-Wall/assets/61572900/8b1632f4-1a2e-4fd7-b65d-4445d06376f4)

![Image](https://github.com/harumas/Gravity-Wall/assets/61572900/469813e5-5160-4326-a795-584566297534)

**Comment by harumas** [comment]
了解

**Comment by harumas** [comment]
これは当たり判定は考慮しない？
考慮するのであれば、今はCinemachineで実装されているから、PlayerObject/VirtualCameraにCinemachine Colliderをつけて確認できるよ。
とりあえずこれで床をすり抜けない動作を確認してもらってもらった方が早いかも。
壁のディザ抜きとの併用を考えているのであれば、これを元に仕様を考えられると思うし。

![image](https://github.com/harumas/Gravity-Wall/assets/43531665/26a85940-5963-4a76-ae8e-61e2ca8f9113)

**Comment by MettoNao** [comment]
動作を確認した。ありがとう。
今、Playerが接地している地面のみを判定する、みたいな事ができれば想定通りの動きになりそう。
ただ、その場合レイヤーで分けるみたいな事ができるのかな？

**Comment by harumas** [comment]
出来るけど、繋がってるメッシュでやるなら難しいね。
やるとしたら、プレイヤーの下半身にカメラが行ったら衝突判定に切り替えるみたいな感じになるかも。

**Comment by MettoNao** [comment]
> やるとしたら、プレイヤーの下半身にカメラが行ったら衝突判定に切り替えるみたいな感じになるかも。

それだと、Playerが角とか壁際にいる時にカメラを上に向けたら、動きがぐちゃぐちゃになる気がする。
カメラが衝突してる壁の法線の方向によってカメラの動きを変える、とかできんかな？

**Comment by harumas** [comment]
法線だけだと、球状とか凹凸とか色々バグりそうだな...

床に埋まるのがしんどいってことなら、
カメラの中心が常にプレイヤーじゃ無いカメラワークみたいなのがあれば問題解決になりそう。

**Comment by MettoNao** [comment]
> 法線だけだと、球状とか凹凸とか色々バグりそうだな...
確かにそうだね

> カメラの中心が常にプレイヤーじゃ無いカメラワークみたいなのがあれば問題解決になりそう。
カメラが下に向くほど、CameraPivotHorizontalのY座標が増加してくみたいな感じ？
それで一回やってみるのもありだな。

**Comment by harumas** [comment]
ちょっと変わるけどオートマタはプレイヤーが常に中心じゃないカメラだね

![Image](https://github.com/harumas/Gravity-Wall/assets/43531665/9fa1490d-db00-497b-9e2a-acb948c8915b)



![Image](https://github.com/harumas/Gravity-Wall/assets/43531665/57715368-3601-471d-8490-db84c872b6ff)



![Image](https://github.com/harumas/Gravity-Wall/assets/43531665/c6d58553-bbe5-446f-9758-45902650001c)



![Image](https://github.com/harumas/Gravity-Wall/assets/43531665/74dc5d3d-6df0-4392-b7e4-ab4bca4969c0)

**Comment by MettoNao** [comment]
キャラと被りそうになったら横にズレるのか。
カメラの角度によって中心が移動するのが良さそうだね。
