### ISSUE TITLE
セーブポイントの修正をする

### ISSUE THREAD

**Issue by MettoNao** [harumas/Gravity-Wall#215]

**Comment by Mocha0924** [comment]
重力方向をセーブポイントごとに変更できるようにしました
他のステージを触っていいのなら、すべてのセーブポイントのを設定を変更しときます
他にセーブ関係で変更してほしい内容はありますか

**Comment by MettoNao** [comment]
SavePointObject.csがエラーを吐いてます
Cinemachineがusingできないって言ってます
そっちで出ていないのならこちらの不手際かもしれませんが、使用していないusingは消したほうが良いです。

あと、一部重力変更が正しく行われていない場所があります
例の動画です。
修正に時間がかかりそうなら、本実装を早めてはるとに任せた方が良いかも。
よろしくお願いします
https://github.com/user-attachments/assets/a6bca411-1184-4d2c-98f8-f2e77553be21

**Comment by Mocha0924** [comment]
了解です。修正してみてまた連絡します
