### ISSUE TITLE
プレイヤーがMesh Colliderの切れ目を移動すると、不自然に大きく揺れる問題を修正する

### ISSUE THREAD

**Issue by MettoNao** [harumas/Gravity-Wall#29]

**Comment by harumas** [comment]
修正しました
・コライダーの切れ目でプレイヤーが不自然に揺れる問題の修正
・繋がっているメッシュ(繋がったメッシュの壁など)で、重力変更が行われない問題の修正

**Comment by MettoNao** [comment]
・コライダーの切れ目でプレイヤーが不自然に揺れる問題の修正
は修正されてます。ありがとう！

ただ、
* 繋がっているメッシュ(繋がったメッシュの壁など)で、重力変更が行われない問題の修正
は俺の環境ではまだ挙動が不安定です。
新しくIssueを立てるのでこれは一旦Doneにしときます。

**Comment by harumas** [comment]
> 繋がっているメッシュ(繋がったメッシュの壁など)で、重力変更が行われない問題の修正
は俺の環境ではまだ挙動が不安定です。

PlaygroundのシーンのPlayerのPrefabをOverrideしてみてもらえますか？
現状の判定方法では、SphereColliderではうまく動作しないので、CapsuleColliderに変えました。

**Comment by MettoNao** [comment]
適切に重力変更が行われるようになりました！
ありがとう！
