### ISSUE TITLE
回転中にジャンプするとジャンプ力がおかしくなってしまう問題の修正

### ISSUE THREAD

**Issue by harumas** [harumas/Gravity-Wall#30]

**Comment by harumas** [comment]
半分くらい起きなくなった。
今は回転中にジャンプを制限することで起きなくしてるんだけど、操作感としてはストレスが大きい。

どこまでを回転中とするかで、発生率とトレードオフになりそう。
回転中の範囲を小さくすると、ジャンプできない時間が短くなるからストレスは少ない。
けれども、この問題は起きやすくなる。逆も然り。

PlayerObjects→Player→PlayerControllerコンポーネント→allow jump angleで調整できます。
この値を大きくすると回転中の範囲が小さくなるので注意。

**Comment by harumas** [comment]
問題の構造的に完全に治すのは難しいかも...
個人的には、マジな話テクニックとして検討してみるのもありだとは思う。ゲーム性変わるけど。.

**Comment by MettoNao** [comment]
了解。忙しい中ありがとう。
大ジャンプでバグるようなレベルデザインは避けた方が良いって感じかな...

**Comment by harumas** [comment]
ジャンプした時のみ重力変更できるとか、重力変更できる場所が限られてて、坂を伝ってのみ重力変更できるとか
その辺の仕様によっても変わりそうだから、仕様固まってからまた模索してみようかなって思ってる。

**Comment by harumas** [comment]
優先度高いのでやり直す

**Comment by harumas** [comment]
治った。けど、角付近で重力が数回変わってしまう問題があるので、それはまたいつか治す
