### ISSUE TITLE
重力変化を一時的に使えなくする機能を実装する

### ISSUE THREAD

**Issue by MettoNao** [harumas/Gravity-Wall#34]
プレイヤーはチュートリアルステージの途中で重力変化の能力を手にいれるため、最初は重力変化の機能が備わっていない。

そのため以下の実装が必要。

- チュートリアルステージロード時にプレイヤーは重力変化をロックされている
- ボックスコライダー(Trigger)内にプレイヤーが侵入した時に重力変化のロックが外れる。(後に何かしらのイベントを出したい)

**Comment by harumas** [comment]
PlayerオブジェクトのGravitySwitcherオブジェクトにEnable(), Disable()メソッドを追加しました。
それで切り替えられます。
あと、重力変化がない状態でも自然に動かせるようにするために、動きを調整したので若干動きが変わってるかもしれない。
