### ISSUE TITLE
貼り付けない壁を実装する

### ISSUE THREAD

**Issue by MettoNao** [harumas/Gravity-Wall#52]
- その壁に触れても重力変化が行われない。普通の壁。

**Comment by harumas** [comment]
そういえば昨日これの実装してなかったっけ？
なおまさがやるなら、今やってるジャンプのバグ修正とコンフリクトしちゃうかも

**Comment by MettoNao** [comment]
いや、結局実装してない
コンフリクトしそうなら引き続き、どっちの実装もはるとにお願いしたい

**Comment by harumas** [comment]
了解

**Comment by harumas** [comment]
実装しました。
貼り付いて欲しくないオブジェクトのレイヤーに`IgnoreGravity`レイヤーを設定すると、貼り付かなくなります。

現状の仕様としては
- 張り付く壁→張り付かない壁: 移動できない
- 張り付かない壁→張り付く壁: 移動できる

貼り付けないといっても、重力が変わらないだけなので
両方とも同じ重力の場合は張り付かない壁にも移動できます。

**Comment by harumas** [comment]
あーこの場合は移動できてしまうな...
![Image](https://github.com/user-attachments/assets/fb6746d7-05ad-41cb-9004-509730079984)

**Comment by MettoNao** [comment]
ここの移動を制限するのは難しい？

**Comment by harumas** [comment]
難しいかも。治そうとすると切れ目のバグとかが出ちゃうから、他の部分が駄目になる。

**Comment by MettoNao** [comment]
了解。この仕様でレベルデザインを進めてみます。
ありがとう。
