### ISSUE TITLE
レベル自動作成時にBuildSettingsのScenes in buildに自動で設定されるようにする

### ISSUE THREAD

**Issue by MettoNao** [harumas/Gravity-Wall#64]

**Comment by harumas** [comment]
実装しました。今は、2つのフォルダーにSceneファイルが作成されたら、BuildSettingsのScenes in buildが更新されるようになっています。

- Scenes/Level
- Scenes/Title

**Comment by harumas** [comment]
あと、最初に実行されるシーンはRoot.unityに固定されてます。
やりづらかったら変えるかも

**Comment by MettoNao** [comment]
実装ありがとう。
Macでバックスラッシュは使えないので、macに対応できるよう書き換えました。
問題なければdevelopにマージしてください。
お願いします。

https://github.com/harumas/Gravity-Wall/pull/68
