### ISSUE TITLE
感度設定機能の追加

### ISSUE THREAD

**Issue by harumas** [harumas/Gravity-Wall#70]

**Comment by harumas** [comment]
感度設定に対応しました。
エディタ上のメニューバー→Tools→GameConfigWindowで設定できます。
再生中しか編集できないので注意してください。

編集したらSaveボタンで保存できます。
保存した設定は、人によって分けられているはずなので、他人に書き換えられるとかは無いと思います。


![Image](https://github.com/user-attachments/assets/3e3ac330-d800-4115-96b9-3c46e7222db5)

**Comment by Mocha0924** [comment]
8/1中に確認します

**Comment by Mocha0924** [comment]
developで確認しようとしたらこのような画面になってしまうのですがどうしたらいいでしょうか？


![Image](https://github.com/user-attachments/assets/d8bbbc96-4564-4b3b-adc9-1bf812d05f1c)


このスクリプトの21行目がnullになっているようです


![Image](https://github.com/user-attachments/assets/5d2ac8bf-98ab-45c5-a92b-b25706f54709)

**Comment by harumas** [comment]
エラー修正しました。もう一度確認お願いします。

**Comment by Mocha0924** [comment]
ありがとうございます
マウスの感度変更は確認できました

現在パッドの感度設定がPad SensibilityではなくMouse Sensibilityに依存しています
あとゲームを再生したときのはじめだけBootingの画面になってしまいます

https://github.com/user-attachments/assets/a1c222f9-4462-4d83-9ce7-ebaa6b967f8b

**Comment by harumas** [comment]
感度が共有されてしまっていたようです... 修正しました。
最初にBootingの画面になるのは、初期化で必要な処理なので大丈夫です。

**Comment by Mocha0924** [comment]
パッドの感度変更も確認できました。ありがとうございます
念のため確認なのですが、プレイヤー用の内容にした時もBootingの画面は出る感じですか？

**Comment by harumas** [comment]
プレイヤー用の内容というのは実際に遊んでもらうときってことですか？
実際の完成版の時はタイトル画面から入るはずなので、そこで初期化処理を挟むのでこの画面は出さないようにします。
開発中は最初からレベルシーンに入るので、初期化シーン(Booting)を一旦経由してから、レベルシーンに入るようにしています。

**Comment by Mocha0924** [comment]
実際に遊んでもらうときであっています
遊んでもらうときに初期化シーンが出ないのなら大丈夫です。ありがとうございます
内容が確認できたので、ステータスをCloseに変更します
ありがとうございました
