### ISSUE TITLE
オブジェクトが引っかかってしまう問題の改善

### ISSUE THREAD

**Issue by harumas** [harumas/Gravity-Wall#73]

**Comment by harumas** [comment]
Unityの物理挙動の設定で、判定のしきい値を変えることで精度をあげられるそうです。
もしかしたら引っ掛かりが減らせるかもしれないので、一旦この設定でステージ制作をお願いします。

developブランチに変更をマージしたので、developの変更を入れれば反映されます。

**Comment by Mocha0924** [comment]
既存のステージで確認してみたところ致命的な引っ掛かりが今のところ確認できなくなりました。ありがとうございます
もう少し確認してからステータスをDoneに変更します
